# Generated by Django 4.1.3 on 2022-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_rename_contact_tb_cnt_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputEmail4', models.CharField(max_length=255)),
                ('inputPassword4', models.CharField(max_length=255)),
                ('inputAddress', models.CharField(max_length=255)),
                ('inputAddress2', models.CharField(max_length=255)),
                ('inputCity', models.CharField(max_length=255)),
                ('inputState', models.CharField(max_length=255)),
                ('inputZip', models.CharField(max_length=255)),
            ],
        ),
    ]
