# Generated by Django 4.1.3 on 2022-12-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_admin_reg_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='productadd_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proimage', models.FileField(upload_to='product/productadd')),
                ('proname', models.CharField(max_length=255)),
                ('proprice', models.CharField(max_length=255)),
                ('prodescrp', models.CharField(max_length=255)),
            ],
        ),
    ]
