# Generated by Django 4.1.3 on 2022-12-09 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_reg_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_tb',
            old_name='email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='reg_tb',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='reg_tb',
            old_name='password',
            new_name='userpassword',
        ),
        migrations.RenameField(
            model_name='reg_tb',
            old_name='phone',
            new_name='userphone',
        ),
    ]
