# Generated by Django 4.1.3 on 2022-12-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_rename_email_reg_tb_useremail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cnt_tb',
            new_name='contct_tb',
        ),
    ]
