# Generated by Django 4.1.3 on 2022-12-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_rename_cnt_tb_contct_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contct_tb',
            old_name='name',
            new_name='usrname',
        ),
    ]
